[package]
name = "solana-cargo-build-bpf"
description = "Compile a local package and all of its dependencies using the Solana SBF SDK"
publish = false
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
cargo_metadata = { workspace = true }
clap = { version = "3.1.5", features = ["cargo", "env"] }
log = { workspace = true, features = ["std"] }
solana-logger = { workspace = true }
solana-sdk = { workspace = true }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
