[package]
name = "solana-sbf-rust-simulation"
description = "Solana SBF Program Simulation Differences"
documentation = "https://docs.rs/solana-sbf-rust-simulation"
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[features]
test-bpf = []

[dependencies]
solana-program = { workspace = true }

[dev-dependencies]
solana-logger = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
solana-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
