[package]
name = "solana-sbf-rust-param-passing-dep"
description = "Solana SBF program written in Rust"
documentation = "https://docs.rs/solana-sbf-rust-param-passing-dep"
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
solana-program = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
