[package]
name = "solana-zk-token-proof-program"
description = "Solana Zk Token Proof Program"
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
getrandom = { workspace = true, features = ["dummy"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-zk-token-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
curve25519-dalek = { workspace = true }

[[bench]]
name = "verify_proofs"
harness = false
