[package]
name = "solana-rayon-threadlimit"
description = "solana-rayon-threadlimit"
documentation = "https://docs.rs/solana-rayon-threadlimit"
readme = "../README.md"
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
lazy_static = { workspace = true }
num_cpus = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
