[package]
name = "solana-cargo-test-bpf"
description = "Execute all unit and integration tests after building with the Solana SBF SDK"
publish = false
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[dependencies]
cargo_metadata = { workspace = true }
clap = { version = "3.1.5", features = ["cargo"] }

[[bin]]
name = "cargo-test-bpf"
path = "src/main.rs"
