# This package only exists to avoid circular dependencies during cargo publish:
# solana-runtime -> solana-address-program -> solana-program-test -> solana-runtime

[package]
name = "solana-address-lookup-table-program-tests"
publish = false
version = "1.17.0"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solanalabs.com/"
license = "Apache-2.0"
edition = "2021"

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
solana-address-lookup-table-program = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
